<?php
namespace http\filter\impl;

/**
 * Test class for InputFilterXss.
 * Generated by PHPUnit on 2014-11-19 at 14:34:58.
 */
class InputFilterXssTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     * @var InputFilterXss
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new InputFilterXss();
    }

    /**
     * @covers compact\http\filter\impl\InputFilterXss::filter
     *
     * @todo Implement testFilter().
     */
    public function testFilterString()
    {
        $str = "'';!--\"<XSS>=&{()}";
        
        $result = $this->object->filter($str);
        $expected = "'';!--\"[removed]=&{()}";
        
        $this->assertEquals($expected, $result);
    }

    /**
     * @covers compact\http\filter\impl\InputFilterXss::filter
     *
     * @todo Implement testFilter().
     */
    public function testFilterWithReplacement()
    {
        $str = "'';!--\"<XSS>=&{()}";
        $this->object->setRemoveReplacementString("[[rem]]");
        
        $result = $this->object->filter($str);
        $expected = "'';!--\"[[rem]]=&{()}";
        
        $this->assertEquals($expected, $result);
    }
}
