<?php
namespace http;

/**
 * Test class for HttpContext.
 * Generated by PHPUnit on 2014-11-19 at 14:39:19.
 */
class HttpContextTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     * @var HttpContext
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = HttpContext::get();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {}

    public function testGetRequest()
    {
        $request = $this->object->getRequest();
        
        $this->assertTrue($request instanceof HttpRequest);
        
        $this->assertTrue($request === $this->object->getRequest(), "Check for Singleton");
    }

    public function testGetResponse()
    {
        $response = $this->object->getResponse();
        
        $this->assertTrue($response instanceof HttpResponse);
        
        $this->assertTrue($response === $this->object->getResponse(), "Check for Singleton");
    }

    public function testGetCookieManager()
    {
        $cookieMgr = $this->object->getCookieManager();
        
        $this->assertTrue($cookieMgr instanceof HttpCookieManager);
        
        $this->assertTrue($cookieMgr === $this->object->getCookieManager(), "Check for Singleton");
    }

    public function testGetSession()
    {
        $session = $this->object->getSession();
        
        $this->assertTrue($session instanceof HttpSession);
        
        $this->assertTrue($session === $this->object->getSession(), "Check for Singleton");
    }
}
