<?php
namespace http;

/**
 * Test class for HttpResponse.
 * Generated by PHPUnit on 2014-11-19 at 14:41:13.
 */
class HttpResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     * @var HttpResponse
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MockHttpResponse();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    	
    }

    /**
     * @covers \http\HttpResponse::getCharSet
     */
    public function testGetCharSet()
    {
        $this->object->setCharSet("UTF-8");
        
        $this->assertEquals($this->object->getCharSet(), "UTF-8");
    }

    /**
     * @covers \http\HttpResponse::getContentType
     */
    public function testGetDefaultContentType()
    {
        $this->assertEquals($this->object->getContentType(), "text/html");
    }
    
    /**
     * @covers \http\HttpResponse::getContentType
     */
    public function testGetContentType()
    {
        $this->object->setContentType("text/xml");
        
        $this->assertEquals($this->object->getContentType(), "text/xml");
    }

    /**
     * @covers \http\HttpResponse::getStatusCode
     */
    public function testGetStatusCode()
    {
        $code = $this->object->getStatusCode();
        
        $this->assertEquals(200, $code, 'Default status code should be 200');
    }

    /**
     * @covers \http\HttpResponse::setStatusCode
     */
    public function testSetStatusCode()
    {
        $this->object->setStatusCode(301);
        $code = $this->object->getStatusCode();
        
        $this->assertEquals(301, $code, 'Status code should be 301');
    }
    
    public function testIsHeaderSendAfterWrite() {
    	$this->assertFalse($this->object->isHeaderSend(), "Headers already send");
    	$this->object->write('test');
    	$this->assertTrue($this->object->isHeaderSend(), "Headers not send");
    }
}

class MockHttpResponse extends HttpResponse {
	
	private $mockHeaders = array();
	private $headersSend = false;
	
	public function isHeaderSend() {
		return $this->headersSend;
	}
	
	protected function sendHeader($aCompleteHeader, $aReplace = false, $aStatusCode = null){
		$this->mockHeaders[] = $aCompleteHeader;
		$this->headersSend = true;
	}
	
	public function write($content) {
		parent::write($content);
		$this->headersSend = true;
	}
}
